name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  SLN_PATH: src/Configuration.Providers
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Go to solution directory
      run: cd $GITHUB_WORKSPACE/$SLN_PATH
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
